### ISSUE TITLE
Implement initial UI framework and views for iOS

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq-client#2]
Bounty: $500 USD*
> *To be compensated via the [Bisq DAO](https://bisq.wiki/Introduction_to_the_DAO) in the USD equivalent of [BSQ](https://bisq.wiki/BSQ) at the time of submitting a [compensation request](https://bisq.wiki/Making_a_compensation_request).

In order to claim the bounty, the following criteria must be satisfied:
- [ ] Written in native Swift using latest framework/libraries.
- [ ] Follows [iOS design guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/overview/themes/).
- [ ] Follows [Swift design guidelines](https://swift.org/documentation/api-design-guidelines/) and a consistent style such as [Google's](https://google.github.io/swift/) or [raywenderlich](https://github.com/raywenderlich/swift-style-guide).
- [ ] Integrates into the project structure, as setup by #1.
- [ ] Builds successfully without errors.
- [ ] Implements the legacy pairing process views following the designs specified [here](https://github.com/bisq-network/bisq-client/wiki/UX-Design#legacy-pairing-process). The pairing process does not need to work, as the business logic will be implemented in #24; just need a click through prototype.
- [ ] Implements a notifications view following the designs specified [here](https://github.com/bisq-network/bisq-client/wiki/UX-Design#notifications). This should be the primary/initial view. Dummy notifications can be generated for demonstration purposes as the actual implementation will be done in #6.
- [ ] Implements a settings view that has options to re-run the pairing process, delete all notifications, mark all as read following the designs specified [here](https://github.com/bisq-network/bisq-client/wiki/UX-Design#settings).

**Comment by devinbileck** [comment]
Closing this as I have split this up into separate issues.
