### ISSUE TITLE
Implement initial UI framework and views for Android

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq-client#3]
Bounty: $500 USD*
> *To be compensated via the [Bisq DAO](https://bisq.wiki/Introduction_to_the_DAO) in the USD equivalent of [BSQ](https://bisq.wiki/BSQ) at the time of submitting a [compensation request](https://bisq.wiki/Making_a_compensation_request).

In order to claim the bounty, the following criteria must be satisfied:
- [ ] Written in native Kotlin using latest framework/libraries.
- [ ] Follows [Android design guidelines](https://developer.android.com/design/).
- [ ] Follows [Kotlin coding conventions](https://kotlinlang.org/docs/coding-conventions.html) and [style guide](https://developer.android.com/kotlin/style-guide).
- [ ] Integrates into the project structure, as setup by #1.
- [ ] Builds successfully without errors.
- [ ] Implements the legacy pairing process views following the designs specified [here](https://github.com/bisq-network/bisq-client/wiki/UX-Design#legacy-pairing-process). The pairing process does not need to work, as the business logic will be implemented in #24; just need a click through prototype.
- [ ] Implements a notifications view following the designs specified [here](https://github.com/bisq-network/bisq-client/wiki/UX-Design#notifications). This should be the primary/initial view. Dummy notifications can be generated for demonstration purposes as the actual implementation will be done in #6.
- [ ] Implements a settings view that has options to re-run the pairing process, delete all notifications, mark all as read following the designs specified [here](https://github.com/bisq-network/bisq-client/wiki/UX-Design#settings).

**Comment by devinbileck** [comment]
Closing this as I have split this up into separate issues.
